version: "3.7"

services:
  gateway:
    build:
      context: gateway/docker/development/nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./frontend:/app

  api:
    build:
      context: backend/docker
      dockerfile: development/nginx/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: backend/docker
      dockerfile: development/php-fpm/Dockerfile
    volumes:
      - ./backend:/app
