all:
  children:
    site:
      hosts:
        server:
          ansible_connection: ssh
          ansible_host: 34.225.193.170
          ansible_user: root
          ansible_ssh_private_key_file: ~/amazonAWS/my-free-amazon-test-server.pem

